use super::models::Taskfile;

/// Export a Taskfile to YAML string
pub fn to_yaml(taskfile: &Taskfile) -> Result<String, String> {
    serde_yaml::to_string(taskfile)
        .map_err(|e| format!("Failed to serialize Taskfile to YAML: {}", e))
}

/// Export a Taskfile to YAML string with custom formatting
pub fn to_yaml_pretty(taskfile: &Taskfile) -> Result<String, String> {
    let yaml = to_yaml(taskfile)?;

    // Add header comment
    let header = format!(
        "# {}.taskfile.yaml\n# Generated by Tasker\n# Schema version: {}\n\n",
        slugify(&taskfile.metadata.name),
        taskfile.taskfile
    );

    Ok(header + &yaml)
}

/// Convert a string to a URL-safe slug
fn slugify(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

/// Suggest a filename for the taskfile
pub fn suggest_filename(taskfile: &Taskfile) -> String {
    format!("{}.taskfile.yaml", slugify(&taskfile.metadata.name))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::taskfile::models::*;

    fn create_minimal_taskfile() -> Taskfile {
        Taskfile {
            taskfile: "1.0".to_string(),
            metadata: TaskfileMetadata {
                name: "Test Workflow".to_string(),
                description: Some("A test workflow".to_string()),
                version: "1.0.0".to_string(),
                author: None,
                tags: vec![],
            },
            triggers: Triggers::default(),
            dependencies: Dependencies::default(),
            limits: Limits::default(),
            variables: vec![],
            execution: ExecutionConfig::default(),
            steps: vec![TaskfileStep {
                id: "navigate".to_string(),
                action: TaskfileAction::Navigate {
                    url: "https://example.com".to_string(),
                },
                description: Some("Go to example.com".to_string()),
                condition: None,
            }],
            output: Output::default(),
        }
    }

    #[test]
    fn test_to_yaml() {
        let taskfile = create_minimal_taskfile();
        let result = to_yaml(&taskfile);
        assert!(result.is_ok());
        let yaml = result.unwrap();
        assert!(yaml.contains("Test Workflow"));
        assert!(yaml.contains("navigate"));
    }

    #[test]
    fn test_slugify() {
        assert_eq!(slugify("Test Workflow"), "test-workflow");
        assert_eq!(slugify("Login to Dashboard!"), "login-to-dashboard");
        assert_eq!(slugify("  Multiple   Spaces  "), "multiple-spaces");
    }
}
